export type Product = {
  slug: string;
  name: string;
  asin: string;
  category: string;
  categorySlug: string;
  categoryName: string;
  price: string;
  priceMin: number;
  rating: number;
  reviewCount: number;
  shortDescription: string;
  fullDescription: string;
  pros: string[];
  cons: string[];
  specs: Record<string, string>;
  badge?: string;
  relatedPosts?: string[];
};

export const categories = [
  { slug: "portatiles", name: "Portátiles para trabajo remoto", description: "Los mejores portátiles para teletrabajar con rendimiento y autonomía", icon: "💻", priceRange: "400€ — 2.500€" },
  { slug: "perifericos", name: "Teclados y ratones", description: "Periféricos ergonómicos para trabajar más cómodo y productivo", icon: "⌨️", priceRange: "20€ — 200€" },
  { slug: "microfonos", name: "Micrófonos para podcast", description: "Micrófonos USB y XLR para grabaciones profesionales en casa", icon: "🎙️", priceRange: "30€ — 250€" },
  { slug: "webcams", name: "Webcams y cámaras", description: "Las mejores webcams para videollamadas y streaming", icon: "📷", priceRange: "25€ — 200€" },
  { slug: "auriculares", name: "Auriculares para trabajar", description: "Auriculares con y sin cancelación de ruido para trabajo remoto", icon: "🎧", priceRange: "20€ — 350€" },
  { slug: "iluminacion", name: "Iluminación para streaming", description: "Paneles LED y ring lights para videollamadas y contenido", icon: "💡", priceRange: "15€ — 300€" },
  { slug: "sillas-ergonomicas", name: "Sillas ergonómicas", description: "Sillas de oficina ergonómicas para jornadas largas de trabajo", icon: "🪑", priceRange: "100€ — 800€" },
  { slug: "escritorios", name: "Escritorios y mesas", description: "Escritorios ajustables en altura y mesas de trabajo", icon: "🖥️", priceRange: "80€ — 600€" },
  { slug: "monitores", name: "Monitores para Home Office", description: "Monitores 4K y QHD para trabajo remoto y home office. Con USB-C, Eye-Care y calibración profesional.", icon: "🖥️", priceRange: "180€ — 450€" },
];

export const products: Product[] = [
  // PORTÁTILES
  {
    slug: "apple-macbook-air-m3-13",
    name: "Apple MacBook Air M3 13\" 8GB 256GB",
    asin: "B0CX242NL1",
    category: "Portátiles",
    categorySlug: "portatiles",
    categoryName: "Portátiles para trabajo remoto",
    price: "€1.299,00",
    priceMin: 1299,
    rating: 4.8,
    reviewCount: 2450,
    shortDescription: "El portátil más equilibrado del mercado: chip M3 con hasta 18h de batería real, pantalla Liquid Retina y 1,24 kg de peso.",
    fullDescription: "El MacBook Air M3 es la evolución del portátil más vendido de Apple. Con el chip M3 de 8 núcleos de CPU y 10 de GPU, ofrece un rendimiento excepcional para ofimática, edición de foto y vídeo ligera, y multitarea con decenas de pestañas abiertas. La pantalla Liquid Retina de 13,6 pulgadas con True Tone y P3 es de las mejores en su segmento. La batería real supera las 15 horas en uso mixto. El sistema de refrigeración sin ventilador garantiza un funcionamiento completamente silencioso.",
    pros: ["Hasta 18h de autonomía real", "Chip M3: rendimiento y eficiencia líderes", "Sin ventilador — completamente silencioso", "Pantalla Liquid Retina P3 de 13,6\"", "Solo 1,24 kg — el más ligero de su categoría"],
    cons: ["Solo 2 puertos USB-C (necesita adaptador para HDMI/USB-A)", "256 GB de base — recomendable subir a 512 GB", "Precio elevado respecto a la competencia Windows"],
    specs: { "Procesador": "Apple M3 (8C CPU + 10C GPU)", "RAM": "8 GB unificada", "Almacenamiento": "256 GB SSD NVMe", "Pantalla": "13,6\" Liquid Retina 2560×1664", "Batería": "Hasta 18h (Apple)", "Peso": "1,24 kg", "Puertos": "2× USB-C / MagSafe 3 / Jack 3,5mm" },
    badge: "Mejor overall",
    relatedPosts: ["mejor-tablet-teletrabajo-2025", "home-office-setup-productivo-guia", "setup-trabajo-remoto-productividad-maxima"],
  },
  {
    slug: "asus-zenbook-14-oled-ux3405",
    name: "ASUS ZenBook 14 OLED UX3405 Intel Core Ultra 7",
    asin: "B0CQXVFR67",
    category: "Portátiles",
    categorySlug: "portatiles",
    categoryName: "Portátiles para trabajo remoto",
    price: "€899,00",
    priceMin: 899,
    rating: 4.5,
    reviewCount: 890,
    shortDescription: "Pantalla OLED 2,8K 120Hz con Intel Core Ultra 7, 16 GB RAM y 15h de batería por menos de 900€.",
    fullDescription: "El ASUS ZenBook 14 OLED UX3405 es la propuesta más completa en la gama de 800-1.000€ para teletrabajo. Su pantalla OLED de 2,8K con 120Hz y 100% de cobertura DCI-P3 es espectacular para edición visual. El procesador Intel Core Ultra 7 gestiona perfectamente la multitarea habitual de oficina y reuniones. Los 16 GB de RAM soldada y el SSD de 512 GB son configuraciones más que suficientes para la mayoría de usos profesionales.",
    pros: ["Pantalla OLED 2,8K 120Hz — espectacular", "16 GB RAM incluidos de serie", "Intel Core Ultra 7 con IA integrada", "Diseño delgado (14,9 mm) y ligero (1,39 kg)", "Puerto HDMI 2.1 incluido (sin adaptador)"],
    cons: ["No tiene lector de tarjetas SD", "La webcam integrada es solo 1080p sin obturador físico", "OLED puede acusar burn-in en uso intensivo a largo plazo"],
    specs: { "Procesador": "Intel Core Ultra 7 155H", "RAM": "16 GB LPDDR5X", "Almacenamiento": "512 GB SSD NVMe", "Pantalla": "14\" OLED 2880×1800 120Hz", "Batería": "Hasta 15h", "Peso": "1,39 kg", "Puertos": "2× USB-C Thunderbolt 4, 1× USB-A, 1× HDMI 2.1, Jack" },
    badge: "Mejor pantalla",
    relatedPosts: ["mejor-tablet-teletrabajo-2025", "home-office-setup-productivo-guia", "setup-trabajo-remoto-productividad-maxima"],
  },
  {
    slug: "lenovo-thinkpad-x1-carbon-gen12",
    name: "Lenovo ThinkPad X1 Carbon Gen 12 Intel Core Ultra 5",
    asin: "B0CRTJ6K3M",
    category: "Portátiles",
    categorySlug: "portatiles",
    categoryName: "Portátiles para trabajo remoto",
    price: "€1.599,00",
    priceMin: 1599,
    rating: 4.6,
    reviewCount: 340,
    shortDescription: "El portátil empresarial de referencia: 1,12 kg, teclado excepcional, certificación MIL-SPEC y 16h de batería.",
    fullDescription: "El ThinkPad X1 Carbon Gen 12 es el portátil empresarial más refinado del mercado. Su construcción en fibra de carbono lo hace excepcionalmente ligero (1,12 kg) y robusto (certificado MIL-STD-810H). El teclado, legendario en la línea ThinkPad, sigue siendo el mejor en cualquier portátil de consumo. Con Intel Core Ultra 5 o 7, el rendimiento es más que suficiente para cualquier tarea profesional exigente.",
    pros: ["El más ligero de su clase: 1,12 kg", "Teclado mejor de cualquier portátil", "Certificación MIL-STD-810H (resistente a caídas, polvo y temperatura)", "16h de batería real en uso mixto", "4 puertos Thunderbolt 4 + USB-A + HDMI"],
    cons: ["Precio premium elevado", "Sin pantalla OLED en la configuración base", "Sin lector de tarjetas SD"],
    specs: { "Procesador": "Intel Core Ultra 5 125U", "RAM": "16 GB LPDDR5", "Almacenamiento": "512 GB SSD NVMe", "Pantalla": "14\" IPS 1920×1200 60Hz", "Batería": "Hasta 16h", "Peso": "1,12 kg", "Certificación": "MIL-STD-810H" },
    badge: "Para profesionales",
    relatedPosts: ["mejor-tablet-teletrabajo-2025", "trabajo-remoto-espana-guia-completa-2025", "home-office-setup-productivo-guia"],
  },
  {
    slug: "hp-pavilion-plus-14-oled",
    name: "HP Pavilion Plus 14 OLED Intel Core i7 16GB 512GB",
    asin: "B0C6FB9VBK",
    category: "Portátiles",
    categorySlug: "portatiles",
    categoryName: "Portátiles para trabajo remoto",
    price: "€749,00",
    priceMin: 749,
    rating: 4.3,
    reviewCount: 1250,
    shortDescription: "OLED 2,8K con Core i7, 16 GB y 512 GB por menos de 750€: la mejor relación calidad-precio para teletrabajo.",
    fullDescription: "El HP Pavilion Plus 14 OLED es la opción más competitiva en la gama de entrada con pantalla OLED. Con resolución 2,8K, Core i7 de 12ª generación, 16 GB de RAM y 512 GB de almacenamiento, cubre perfectamente las necesidades de cualquier teletrabajador. La pantalla OLED con 100% DCI-P3 lo hace ideal también para diseñadores gráficos con presupuesto ajustado.",
    pros: ["Pantalla OLED 2,8K a precio competitivo", "16 GB RAM y 512 GB SSD de serie", "Intel Core i7 para multitarea exigente", "Lector de tarjetas microSD incluido", "Precio muy competitivo para lo que ofrece"],
    cons: ["Autonomía algo inferior (8-10h reales)", "Peso de 1,46 kg, algo por encima de competidores", "Refresco de 60Hz (no 90/120Hz como otros OLED)"],
    specs: { "Procesador": "Intel Core i7-1255U", "RAM": "16 GB DDR4", "Almacenamiento": "512 GB SSD NVMe", "Pantalla": "14\" OLED 2880×1800 60Hz", "Batería": "Hasta 10h", "Peso": "1,46 kg", "Puertos": "2× USB-C, 2× USB-A, HDMI, microSD" },
    badge: "Mejor relación calidad-precio",
    relatedPosts: ["mejor-tablet-teletrabajo-2025", "home-office-setup-productivo-guia", "setup-trabajo-remoto-productividad-maxima"],
  },

  // PERIFÉRICOS
  {
    slug: "logitech-mx-keys-advanced-s",
    name: "Logitech MX Keys Advanced S Teclado Inalámbrico",
    asin: "B0B2R5VP5V",
    category: "Periféricos",
    categorySlug: "perifericos",
    categoryName: "Teclados y ratones",
    price: "€119,99",
    priceMin: 119,
    rating: 4.6,
    reviewCount: 3200,
    shortDescription: "El teclado inalámbrico de referencia para productividad: teclas esféricas, retroiluminación inteligente y conexión a 3 dispositivos.",
    fullDescription: "El Logitech MX Keys Advanced S es el estándar de facto en teclados de membrana premium para oficina. Sus teclas esféricas con forma perfectamente adaptada a los dedos y la respuesta táctil suave pero precisa lo convierten en una herramienta de escritura excepcional durante horas. La retroiluminación Smart se activa al acercar las manos. Conecta hasta 3 dispositivos simultáneamente (Bluetooth y receptor Logi Bolt) y cambia entre ellos con un solo botón.",
    pros: ["Teclas esféricas de alta calidad — escritura excepcional", "Conexión a 3 dispositivos (Bluetooth + Logi Bolt)", "Retroiluminación inteligente por proximidad", "Compatible con Windows, macOS, Linux, iOS, Android", "Batería hasta 10 días con luz, hasta 5 meses sin"],
    cons: ["No es mecánico (membrana premium)", "Precio elevado para un teclado de membrana", "No tiene teclado numérico en la versión compacta"],
    specs: { "Tipo": "Membrana premium", "Conexión": "Bluetooth / Logi Bolt USB", "Dispositivos": "Hasta 3 simultáneos", "Retroiluminación": "Sí (inteligente por proximidad)", "Batería": "Hasta 10 días (con luz) / 5 meses (sin luz)", "Compatible": "Windows / macOS / Linux / iOS / Android" },
    badge: "Más vendido",
    relatedPosts: ["mejor-teclado-raton-trabajo-remoto", "logitech-mx-keys-analisis-opinion", "setup-trabajo-remoto-productividad-maxima"],
  },
  {
    slug: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S Ratón Inalámbrico",
    asin: "B09HM94VDS",
    category: "Periféricos",
    categorySlug: "perifericos",
    categoryName: "Teclados y ratones",
    price: "€99,99",
    priceMin: 99,
    rating: 4.7,
    reviewCount: 5800,
    shortDescription: "El ratón de productividad más valorado: rueda de desplazamiento electromagnética, 8.000 DPI y clic silencioso 90% más silencioso.",
    fullDescription: "El Logitech MX Master 3S es el ratón más valorado del mercado para trabajo intensivo. Su rueda de desplazamiento MagSpeed electromagnética cambia automáticamente entre modo táctil (paso a paso) y modo libre (desplaza 1.000 líneas por segundo en documentos largos). El sensor óptico de 8.000 DPI funciona en cualquier superficie incluyendo cristal. Los clics son un 90% más silenciosos que en el modelo anterior.",
    pros: ["Rueda MagSpeed: el mejor scroll del mercado", "Funciona sobre cristal y superficies especiales", "8.000 DPI con ajuste de precisión para imagen", "Conexión a 3 dispositivos simultáneos", "Carga USB-C, 70 días con carga completa"],
    cons: ["Precio elevado", "Talla única — puede ser grande para manos pequeñas", "Solo para diestros"],
    specs: { "Sensor": "8.000 DPI óptico", "Conexión": "Bluetooth / Logi Bolt", "Dispositivos": "Hasta 3", "Rueda": "MagSpeed electromagnética", "Batería": "70 días con carga completa", "Carga": "USB-C (1 min = 3h de uso)" },
    badge: "El mejor ratón",
    relatedPosts: ["mejor-teclado-raton-trabajo-remoto", "setup-trabajo-remoto-productividad-maxima", "herramientas-productividad-trabajo-remoto-2025"],
  },
  {
    slug: "keychron-k2-pro-mecanico",
    name: "Keychron K2 Pro Teclado Mecánico Inalámbrico RGB",
    asin: "B0BKLNBPPH",
    category: "Periféricos",
    categorySlug: "perifericos",
    categoryName: "Teclados y ratones",
    price: "€89,99",
    priceMin: 89,
    rating: 4.5,
    reviewCount: 1450,
    shortDescription: "Teclado mecánico compacto 75% con switches hot-swap, compatible Windows/Mac y retroiluminación RGB.",
    fullDescription: "El Keychron K2 Pro es el teclado mecánico compacto más popular para teletrabajo. En formato 75% (con flechas y teclas de función pero sin bloque numérico), incluye soporte hot-swap para cambiar los switches sin soldar. Compatible con Windows y macOS (incluye keycaps para ambos sistemas). Conecta por Bluetooth (3 dispositivos) o cable USB-C. Disponible con switches Gateron G Pro (Red, Brown, Blue).",
    pros: ["Hot-swap: cambia switches sin soldar", "Formato 75% compacto pero funcional", "Compatible Windows y macOS de serie", "Bluetooth 3 dispositivos + cable USB-C", "RGB retroiluminación por tecla"],
    cons: ["Layout ANSI (teclas en inglés por defecto)", "Sin número numérico", "La batería dura menos con RGB activo"],
    specs: { "Tipo": "Mecánico (Gateron G Pro)", "Formato": "75% (84 teclas)", "Conexión": "Bluetooth 5.1 / USB-C", "Hot-swap": "Sí", "RGB": "Sí (por tecla)", "Compatible": "Windows / macOS" },
    relatedPosts: ["mejor-teclado-raton-trabajo-remoto", "logitech-mx-keys-analisis-opinion", "herramientas-productividad-trabajo-remoto-2025"],
  },

  // MICRÓFONOS
  {
    slug: "blue-yeti-usb-microfono",
    name: "Blue Yeti Micrófono USB Condensador para Podcast y Streaming",
    asin: "B00N1YPXW2",
    category: "Micrófonos",
    categorySlug: "microfonos",
    categoryName: "Micrófonos para podcast",
    price: "€129,99",
    priceMin: 129,
    rating: 4.6,
    reviewCount: 8900,
    shortDescription: "El micrófono USB más popular del mundo: 4 patrones polares, monitorización en tiempo real y control de ganancia integrado.",
    fullDescription: "El Blue Yeti es la referencia absoluta en micrófonos USB para podcast, streaming y grabación de voz profesional. Sus tres cápsulas de condensador con 4 patrones polares seleccionables (cardioide, bidireccional, omnidireccional y estéreo) lo hacen extremadamente versátil. El volumen de los auriculares y la ganancia del micrófono se controlan directamente desde el dispositivo. Incluye soporte de escritorio con rosca estándar 5/8\".",
    pros: ["4 patrones polares — máxima versatilidad", "Monitorización en tiempo real sin latencia", "Control de ganancia y silencio directos en el micrófono", "Plug & play — sin drivers ni software necesario", "Soporte de escritorio incluido"],
    cons: ["Tamaño considerable — ocupa espacio en el escritorio", "Sin conector XLR (solo USB)", "El soporte incluido no es el más estable"],
    specs: { "Tipo": "Condensador USB", "Patrones": "4 (cardioide, bidireccional, omni, estéreo)", "Conexión": "USB-A", "Frecuencia": "20 Hz – 20 kHz", "Resolución": "16-bit / 48 kHz", "Monitorización": "Sin latencia" },
    badge: "Referencia del sector",
    relatedPosts: ["mejor-webcam-videollamadas-trabajo-remoto", "como-empezar-negocio-online-desde-casa-2025", "setup-trabajo-remoto-productividad-maxima"],
  },
  {
    slug: "hyperx-solocast-microfono",
    name: "HyperX SoloCast Micrófono USB Condensador Cardioide",
    asin: "B08KFL3SFV",
    category: "Micrófonos",
    categorySlug: "microfonos",
    categoryName: "Micrófonos para podcast",
    price: "€49,99",
    priceMin: 49,
    rating: 4.5,
    reviewCount: 4200,
    shortDescription: "El mejor micrófono USB por menos de 50€: cardioide, tap-to-mute y compatible con PS5, PS4, PC y Mac.",
    fullDescription: "El HyperX SoloCast es la mejor opción para quienes buscan calidad profesional con presupuesto ajustado. Con patrón cardioide optimizado para voz individual, captura la voz con claridad y rechaza el sonido ambiente efectivamente. El botón tap-to-mute con LED de estado es muy práctico para reuniones de trabajo. Compatible con prácticamente cualquier dispositivo: PC, Mac, PS4, PS5.",
    pros: ["Excelente relación calidad-precio", "Tap-to-mute con LED de estado visible", "Soporte flexible con clip para brazo de micrófono", "Compatibilidad universal (PC, Mac, PS4, PS5)", "Plug & play sin instalación"],
    cons: ["Solo patrón cardioide (no versátil para entrevistas)", "Sin monitorización de auriculares", "Sin control de ganancia en el cuerpo"],
    specs: { "Tipo": "Condensador USB cardioide", "Conexión": "USB-C", "Frecuencia": "20 Hz – 20 kHz", "Resolución": "16-bit / 48 kHz", "Mute": "Tap-to-mute con LED", "Montura": "Rosca 3/8\" y 5/8\"" },
    badge: "Mejor relación calidad-precio",
    relatedPosts: ["como-empezar-negocio-online-desde-casa-2025", "mejor-webcam-videollamadas-trabajo-remoto"],
  },
  {
    slug: "rode-nt-usb-mini-microfono",
    name: "Rode NT-USB Mini Micrófono de Condensador USB",
    asin: "B085M7SSVS",
    category: "Micrófonos",
    categorySlug: "microfonos",
    categoryName: "Micrófonos para podcast",
    price: "€99,00",
    priceMin: 99,
    rating: 4.4,
    reviewCount: 2100,
    shortDescription: "Calidad de estudio en formato compacto: ganancia ajustable, monitorización sin latencia y sonido Rode característico.",
    fullDescription: "El Rode NT-USB Mini trae la calidad de audio característica de la marca australiana Rode en un formato compacto y asequible. Su cápsula de condensador de alta calidad captura la voz con un rango de frecuencia amplio y natural. El control de ganancia y la mezcla de monitorización permiten ajustar el volumen sin tocar el ordenador. La base magnética facilita la posición del micrófono en cualquier ángulo.",
    pros: ["Calidad de audio Rode — premium en su gama", "Base magnética para posicionamiento flexible", "Control de ganancia y mezcla integrados", "Monitorización de auriculares sin latencia", "Compatibilidad con iPad (adaptador necesario)"],
    cons: ["Sin patrón polar ajustable (solo cardioide)", "El cable USB-C incluido es corto (apenas 30 cm)", "Sin botón de mute integrado"],
    specs: { "Tipo": "Condensador USB cardioide", "Conexión": "USB-C", "Frecuencia": "20 Hz – 20 kHz", "Ganancia": "Ajustable en el micrófono", "Monitorización": "Sin latencia (jack 3,5mm)", "Base": "Magnética ajustable" },
    relatedPosts: ["como-empezar-negocio-online-desde-casa-2025", "mejor-webcam-videollamadas-trabajo-remoto"],
  },

  // WEBCAMS
  {
    slug: "logitech-c920-hd-pro-webcam",
    name: "Logitech C920 HD Pro Webcam Full HD 1080p 30fps",
    asin: "B006A2Q81M",
    category: "Webcams",
    categorySlug: "webcams",
    categoryName: "Webcams y cámaras",
    price: "€79,99",
    priceMin: 79,
    rating: 4.5,
    reviewCount: 12500,
    shortDescription: "La webcam más vendida del mundo: 1080p 30fps, dos micrófonos estéreo y corrección de luz automática.",
    fullDescription: "La Logitech C920 es la webcam de referencia absoluta en oficinas, creadores de contenido y educadores de todo el mundo. Con resolución Full HD 1080p, dos micrófonos estéreo integrados con cancelación de ruido y corrección automática de luz HD, ofrece una calidad de imagen excelente en cualquier condición. Compatible con todas las plataformas de videollamada: Zoom, Teams, Meet, Skype. El clip universal se adapta a monitores, portátiles y trípodes.",
    pros: ["La más vendida del mundo — soporte y comunidad enormes", "Doble micrófono estéreo con cancelación de ruido", "Corrección automática de luz HD", "Compatible con Windows, macOS y Chrome OS", "Clip universal para monitor, portátil y trípode"],
    cons: ["Máximo 30fps (no 60fps)", "Sin obturador de privacidad físico", "Los micrófonos captan algo de ruido ambiente"],
    specs: { "Resolución": "1080p Full HD", "FPS": "30fps (1080p)", "Micrófonos": "Dual estéreo con cancelación de ruido", "Campo visual": "78°", "Conexión": "USB-A", "Compatible": "Windows / macOS / Chrome OS" },
    badge: "Más vendida",
    relatedPosts: ["mejor-webcam-videollamadas-trabajo-remoto", "como-empezar-negocio-online-desde-casa-2025", "iluminacion-videollamadas-home-office"],
  },
  {
    slug: "logitech-brio-4k-webcam",
    name: "Logitech Brio 4K Ultra HD Webcam con HDR y corrección de luz",
    asin: "B01N5UOYC4",
    category: "Webcams",
    categorySlug: "webcams",
    categoryName: "Webcams y cámaras",
    price: "€169,99",
    priceMin: 169,
    rating: 4.4,
    reviewCount: 4800,
    shortDescription: "Webcam 4K con HDR, Windows Hello y campo visual ajustable de 65°, 78° o 90°.",
    fullDescription: "La Logitech Brio es la webcam más avanzada del catálogo Logitech. Con resolución 4K Ultra HD y tecnología HDR, ofrece una imagen espectacular incluso con contraluz. El campo visual es ajustable entre 65°, 78° y 90° según la situación. Incluye soporte para Windows Hello (autenticación facial infrarroja). Tres micrófonos con supresión de ruido captan la voz con claridad desde cualquier ángulo.",
    pros: ["4K Ultra HD con HDR — imagen excepcional", "Campo visual ajustable (65°/78°/90°)", "Windows Hello para autenticación facial", "3 micrófonos con supresión de ruido", "Obturador de privacidad físico incluido"],
    cons: ["Precio muy elevado", "4K real solo con USB 3.0 (limitado a 1080p con USB 2.0)", "Requiere buena iluminación para aprovechar el 4K"],
    specs: { "Resolución": "4K Ultra HD (2160p)", "FPS": "30fps (4K) / 60fps (1080p)", "Micrófonos": "3 con supresión de ruido", "Campo visual": "65°/78°/90° ajustable", "Windows Hello": "Sí (IR)", "Privacidad": "Obturador físico" },
    relatedPosts: ["mejor-webcam-videollamadas-trabajo-remoto", "iluminacion-videollamadas-home-office", "setup-trabajo-remoto-productividad-maxima"],
  },

  // AURICULARES
  {
    slug: "sony-wh-1000xm5-auriculares",
    name: "Sony WH-1000XM5 Auriculares Inalámbricos ANC 30h",
    asin: "B09XS7JWHH",
    category: "Auriculares",
    categorySlug: "auriculares",
    categoryName: "Auriculares para trabajar",
    price: "€279,00",
    priceMin: 279,
    rating: 4.7,
    reviewCount: 6500,
    shortDescription: "La cancelación de ruido más avanzada del mercado: 8 micrófonos, 30h de batería y plegable para viaje.",
    fullDescription: "Los Sony WH-1000XM5 son los auriculares de cancelación de ruido de referencia absoluta. Con 8 micrófonos y dos procesadores dedicados, su ANC bloquea eficazmente ruidos de oficina, tráfico y conversaciones. La calidad de audio es excepcional con los códecs LDAC y AAC. El modo Speak-to-Chat pausa la música automáticamente cuando hablas. Hasta 30 horas de batería con ANC activo, y carga rápida (3 minutos = 3 horas).",
    pros: ["Mejor ANC del mercado para ruidos constantes", "30h de batería con ANC", "Carga rápida: 3 min = 3h", "Micrófono de llamadas excelente", "Modo Speak-to-Chat automático"],
    cons: ["No se pliegan planos (solo articulados)", "Precio elevado", "Sin conexión por cable activo (solo pasivo)"],
    specs: { "ANC": "8 micrófonos, 2 procesadores dedicados", "Batería": "30h con ANC / 40h sin ANC", "Carga": "USB-C, carga rápida 3min=3h", "Bluetooth": "5.2, multipoint (2 dispositivos)", "Códecs": "LDAC / AAC / SBC", "Peso": "250 g" },
    badge: "Los mejores ANC",
    relatedPosts: ["mejores-auriculares-cancelacion-ruido-trabajo-2025", "sony-wh1000xm5-analisis-opinion", "productividad-trabajando-desde-casa-habitos"],
  },
  {
    slug: "jabra-evolve2-55-auriculares",
    name: "Jabra Evolve2 55 Auriculares Profesionales ANC UC Stereo",
    asin: "B08QHF3KZS",
    category: "Auriculares",
    categorySlug: "auriculares",
    categoryName: "Auriculares para trabajar",
    price: "€349,00",
    priceMin: 349,
    rating: 4.5,
    reviewCount: 1200,
    shortDescription: "El auricular profesional para comunicaciones: 6 micrófonos, ANC avanzado y certificado para Teams, Zoom y Google Meet.",
    fullDescription: "Los Jabra Evolve2 55 son los auriculares diseñados específicamente para comunicaciones empresariales. Con 6 micrófonos de alta calidad en la diadema y en el boom mic opcional, captura la voz con una claridad excepcional y filtra el ruido ambiente de forma agresiva. Certificados para Microsoft Teams, Zoom y Google Meet. La función de concentración permite trabajar en entornos abiertos de oficina sin distracciones.",
    pros: ["6 micrófonos — voz cristalina en llamadas", "Certificado para Teams, Zoom y Meet", "Función de concentración (HearThrough ajustable)", "36h de batería con ANC", "Carga rápida inalámbrica Qi"],
    cons: ["Precio muy elevado", "Diseño menos cómodo para uso prolongado que Sony", "La app requiere registro"],
    specs: { "Micrófonos": "6 integrados en la diadema", "Batería": "36h con ANC", "Certificación": "Microsoft Teams / Zoom / Google Meet", "Carga": "USB-C + Qi inalámbrico", "Bluetooth": "5.0, multipoint", "ANC": "Avanzado ajustable" },
    badge: "Para profesionales",
    relatedPosts: ["mejores-auriculares-cancelacion-ruido-trabajo-2025", "setup-trabajo-remoto-productividad-maxima"],
  },
  {
    slug: "jbl-tune-510bt-auriculares",
    name: "JBL Tune 510BT Auriculares Inalámbricos Bluetooth 40h",
    asin: "B099XHSHQ8",
    category: "Auriculares",
    categorySlug: "auriculares",
    categoryName: "Auriculares para trabajar",
    price: "€39,99",
    priceMin: 39,
    rating: 4.3,
    reviewCount: 5600,
    shortDescription: "Auriculares inalámbricos JBL con 40h de batería, Pure Bass y micrófono integrado por menos de 40€.",
    fullDescription: "Los JBL Tune 510BT son la opción más accesible para quienes necesitan auriculares inalámbricos de calidad para videollamadas y música. Con tecnología Pure Bass de JBL, el sonido es sorprendentemente bueno para su precio. La batería de 40 horas es excelente. El micrófono integrado, aunque básico, funciona correctamente para llamadas. Plegables para guardar en bolsa.",
    pros: ["40h de batería — excepcionales para su precio", "Sonido Pure Bass JBL de calidad", "Plegables y ligeros (160g)", "Multiconexión hasta 2 dispositivos", "Precio imbatible"],
    cons: ["Sin ANC (no aíslan bien en entornos ruidosos)", "Sin carga rápida", "Micrófono básico — suficiente pero no profesional"],
    specs: { "Batería": "40h Bluetooth / 2h carga", "Bluetooth": "5.0, multipoint 2 dispositivos", "Controlador": "32mm Pure Bass", "Plegable": "Sí", "Peso": "160 g", "Carga": "USB-C" },
    badge: "Mejor precio",
    relatedPosts: ["mejores-auriculares-cancelacion-ruido-trabajo-2025", "sony-wh1000xm5-analisis-opinion"],
  },

  // ILUMINACIÓN
  {
    slug: "elgato-key-light-air",
    name: "Elgato Key Light Air Panel LED 1400 lúmenes para Streaming",
    asin: "B082QHRZFW",
    category: "Iluminación",
    categorySlug: "iluminacion",
    categoryName: "Iluminación para streaming",
    price: "€99,99",
    priceMin: 99,
    rating: 4.5,
    reviewCount: 3400,
    shortDescription: "Panel LED profesional para streaming: 1.400 lúmenes, temperatura ajustable 2.900-7.000K y control por app o Stream Deck.",
    fullDescription: "El Elgato Key Light Air es la solución de iluminación preferida por streamers y creadores de contenido profesionales. Con 1.400 lúmenes de potencia y temperatura de color ajustable entre 2.900 K (cálido) y 7.000 K (frío), ofrece una luz difusa y uniforme sin sombras duras. Se controla completamente desde la app Elgato Control Center o desde un Stream Deck. El diseño ultrafino con 80 LEDs sin difusor produce una luz de alta calidad que no calienta.",
    pros: ["Control total por app y Stream Deck", "Temperatura 2.900-7.000K — toda la gama de color", "1.400 lúmenes potentes sin deslumbrar", "Diseño ultradelgado sin calor", "Sin interferencias con cámaras (sin parpadeo)"],
    cons: ["Precio elevado para iluminación básica", "Requiere conexión WiFi para el control por app", "Solo un foco — para iluminación completa necesitas dos"],
    specs: { "Potencia": "1.400 lúmenes", "Temperatura": "2.900 K – 7.000 K ajustable", "LEDs": "80 LEDs de alta densidad", "Control": "App + Stream Deck + Elgato Hub", "Conexión": "WiFi + alimentación por cable", "Calor": "Sin calentamiento" },
    badge: "Elección de streamers",
    relatedPosts: ["iluminacion-videollamadas-home-office", "mejor-webcam-videollamadas-trabajo-remoto"],
  },
  {
    slug: "neewer-ring-light-18-pulgadas",
    name: "Neewer Ring Light 18\" con soporte, trípode y portatarjetas",
    asin: "B01N3ONOQY",
    category: "Iluminación",
    categorySlug: "iluminacion",
    categoryName: "Iluminación para streaming",
    price: "€45,99",
    priceMin: 45,
    rating: 4.4,
    reviewCount: 8900,
    shortDescription: "Ring light 18 pulgadas con temperatura 3.200-5.500K, trípode ajustable hasta 2 m y soporte para teléfono incluido.",
    fullDescription: "La Neewer Ring Light de 18 pulgadas es la opción más popular del mercado para YouTubers, streamers y creadores de contenido con presupuesto ajustado. Con temperatura de color ajustable entre 3.200 K y 5.500 K y 10 niveles de brillo, permite una iluminación muy versátil. El trípode incluido es ajustable hasta 2 metros de altura. El soporte para teléfono facilita grabar vídeo con el móvil.",
    pros: ["Precio muy competitivo — completo kit incluido", "Ring light de 18\" — luz uniforme y envolvente", "Temperatura 3.200-5.500K ajustable", "Trípode hasta 2 m de altura incluido", "Soporte para móvil incluido"],
    cons: ["Calidad de construcción ajustada al precio", "El trípode no es el más estable en superficies irregulares", "Sin control por app ni integración con software de streaming"],
    specs: { "Diámetro": "18 pulgadas (46 cm)", "Temperatura": "3.200 K – 5.500 K", "Brillo": "10 niveles", "Trípode": "Hasta 2 m ajustable", "Alimentación": "Cable con adaptador de pared", "Incluye": "Soporte móvil + adaptador hot shoe" },
    badge: "Mejor relación calidad-precio",
    relatedPosts: ["iluminacion-videollamadas-home-office", "mejor-webcam-videollamadas-trabajo-remoto"],
  },

  // SILLAS ERGONÓMICAS
  {
    slug: "sihoo-m57-silla-ergonomica",
    name: "SIHOO M57 Silla Ergonómica de Oficina con Soporte Lumbar",
    asin: "B09MZDSJXQ",
    category: "Sillas ergonómicas",
    categorySlug: "sillas-ergonomicas",
    categoryName: "Sillas ergonómicas",
    price: "€249,00",
    priceMin: 249,
    rating: 4.4,
    reviewCount: 2800,
    shortDescription: "Silla ergonómica con soporte lumbar 3D, reposacabezas ajustable, asiento en malla y 150 kg de capacidad.",
    fullDescription: "La SIHOO M57 es la silla ergonómica de mayor éxito en el segmento de precio medio. Con respaldo de malla transpirable que favorece la postura y evita el calentamiento de la espalda, soporte lumbar ajustable en altura y profundidad, y reposacabezas regulable, cubre todas las necesidades ergonómicas de una jornada laboral larga. Los reposabrazos en 4D (arriba/abajo, adelante/atrás, rotación) se adaptan a cualquier mesa y configuración.",
    pros: ["Soporte lumbar 3D ajustable en altura y profundidad", "Malla transpirable — no se calienta la espalda", "Reposabrazos 4D muy versátiles", "150 kg de capacidad de carga", "Relación calidad-precio excelente"],
    cons: ["El mecanismo de reclinación podría ser más suave", "El reposacabezas tarda en ajustarse correctamente", "Sin reposapies incluido"],
    specs: { "Respaldo": "Malla transpirable", "Soporte lumbar": "3D (altura + profundidad ajustable)", "Reposacabezas": "Ajustable en altura e inclinación", "Reposabrazos": "4D", "Capacidad": "150 kg", "Reclinación": "90°-135°" },
    badge: "Mejor calidad-precio",
    relatedPosts: ["mejor-silla-ergonomica-home-office-2025", "sihoo-m57-analisis-opinion", "dolor-espalda-trabajar-casa-soluciones"],
  },
  {
    slug: "hbada-silla-ergonomica-pro",
    name: "Hbada Silla Ergonómica de Escritorio Reclinable con Apoyabrazos",
    asin: "B085ZPCBMQ",
    category: "Sillas ergonómicas",
    categorySlug: "sillas-ergonomicas",
    categoryName: "Sillas ergonómicas",
    price: "€189,00",
    priceMin: 189,
    rating: 4.2,
    reviewCount: 4500,
    shortDescription: "Silla de oficina con respaldo reclinable hasta 155°, malla transpirable y reposabrazos plegables.",
    fullDescription: "La Hbada es una de las sillas ergonómicas más vendidas en Amazon España en la gama de menos de 200€. Con respaldo de malla transpirable y mecanismo de reclinación hasta 155°, es especialmente cómoda para quien trabaja muchas horas y le gusta poder reclinarse. Los reposabrazos se pliegan para guardar la silla o cuando no se necesitan. El asiento acolchado con altura regulable se adapta a personas de diferente estatura.",
    pros: ["Reclinación hasta 155° — muy cómoda para descanso", "Reposabrazos plegables (prácticos para espacios pequeños)", "Precio muy accesible", "Malla transpirable en respaldo", "Soporte lumbar integrado en el respaldo"],
    cons: ["El soporte lumbar no es ajustable de forma independiente", "Capacidad máxima de 120 kg (inferior a competidores)", "Sin reposacabezas ajustable"],
    specs: { "Respaldo": "Malla transpirable", "Reclinación": "Hasta 155°", "Reposabrazos": "Plegables 2D", "Capacidad": "120 kg", "Altura asiento": "43-53 cm", "Material base": "Nylon reforzado" },
    relatedPosts: ["mejor-silla-ergonomica-home-office-2025", "dolor-espalda-trabajar-casa-soluciones"],
  },

  // ESCRITORIOS
  {
    slug: "flexispot-e7-pro-escritorio-ajustable",
    name: "FlexiSpot E7 Pro Escritorio Eléctrico Ajustable en Altura 140×70cm",
    asin: "B08C6JFNHQ",
    category: "Escritorios",
    categorySlug: "escritorios",
    categoryName: "Escritorios y mesas",
    price: "€449,00",
    priceMin: 449,
    rating: 4.5,
    reviewCount: 1800,
    shortDescription: "Escritorio ajustable eléctrico de doble motor: 140×70 cm, de 58 a 123 cm de altura y 125 kg de capacidad.",
    fullDescription: "El FlexiSpot E7 Pro es el escritorio ajustable eléctrico de referencia para oficina en casa. Con sistema de doble motor sincronizado, sube y baja de 58 a 123 cm con una velocidad de 4 cm/s. La pantalla LED integrada guarda 4 alturas predefinidas. El tablero de 140×70 cm en melamina de 18mm ofrece espacio suficiente para dos monitores, teclado, ratón y accesorios. La estructura en forma de H garantiza una estabilidad excepcional sin oscilaciones laterales.",
    pros: ["Doble motor — más estable y silencioso que los de un motor", "4 alturas guardadas en memoria", "Capacidad de 125 kg — para cualquier setup", "Garantía de 5 años en el motor", "Subida y bajada suave en 4 cm/s"],
    cons: ["Precio elevado", "Montaje requiere dos personas (estructura pesada)", "Sin gestión de cables incluida"],
    specs: { "Rango de altura": "58 – 123 cm", "Velocidad": "4 cm/s", "Capacidad": "125 kg", "Tablero": "140×70 cm melamina 18mm", "Motores": "Doble motor sincronizado", "Memoria": "4 alturas predefinidas", "Garantía": "5 años en motor" },
    badge: "Mejor escritorio ajustable",
    relatedPosts: ["escritorio-regulable-altura-home-office", "flexispot-e7-pro-analisis-opinion", "home-office-setup-productivo-guia"],
  },
  {
    slug: "flexispot-eg1-escritorio-ajustable",
    name: "FlexiSpot EG1 Escritorio Eléctrico Ajustable 120×60cm",
    asin: "B08GQ2TXFC",
    category: "Escritorios",
    categorySlug: "escritorios",
    categoryName: "Escritorios y mesas",
    price: "€199,00",
    priceMin: 199,
    rating: 4.3,
    reviewCount: 2400,
    shortDescription: "El escritorio ajustable más accesible de FlexiSpot: motor único, 120×60 cm y de 71 a 121 cm de altura.",
    fullDescription: "El FlexiSpot EG1 es la versión más económica de la gama ajustable de FlexiSpot, ideal para quienes quieren probar el concepto de escritorio de pie/sentado sin una gran inversión. Con motor único y estructura en C, ofrece una estabilidad correcta para un setup de un monitor. El rango de altura va de 71 a 121 cm, cubriendo a usuarios de entre 160 y 195 cm de estatura.",
    pros: ["Precio de entrada muy competitivo", "Marca reconocida (FlexiSpot)", "Motor silencioso con detección de obstáculos", "Compatible con tableros IKEA (LINNMON, BEKANT)", "3 años de garantía en motor"],
    cons: ["Un solo motor — algo menos estable que el E7 con carga alta", "Solo 2 alturas en memoria (sin pantalla LED completa)", "Tablero básico — muchos optan por comprar uno aparte"],
    specs: { "Rango de altura": "71 – 121 cm", "Capacidad": "70 kg", "Tablero": "120×60 cm", "Motores": "Un motor", "Memoria": "2 alturas", "Garantía": "3 años en motor" },
    badge: "Mejor precio",
    relatedPosts: ["escritorio-regulable-altura-home-office", "home-office-setup-productivo-guia"],
  },

  // MONITORES
  // priceMin: 0 = precio no fijado (se muestra "Consultar precio" y el schema
  // de producto omite el campo price en lugar de declarar un importe falso).
  {
    slug: "lg-27u730-monitor-4k",
    name: "LG 27U730A-B Monitor 4K 27\" — IPS, USB-C, Eye Care",
    asin: "B0FKBRLWNW",
    category: "Monitores",
    categorySlug: "monitores",
    categoryName: "Monitores para Home Office",
    price: "Consultar precio",
    priceMin: 0,
    rating: 4.4,
    reviewCount: 120,
    shortDescription: "Monitor 4K UHD 27\" IPS con USB-C, DisplayHDR, Eye Care y diseño sin bordes. Para trabajo remoto y diseño.",
    fullDescription: "El LG 27U730A-B es un monitor 4K UHD de 27 pulgadas con panel IPS, pensado para quien pasa la jornada trabajando con texto. A 3840×2160 en 27\", la densidad de píxeles ronda los 163 PPI, de modo que el texto se ve perfectamente definido y la fatiga visual se reduce en jornadas largas. Incorpora conectividad USB-C, soporte DisplayHDR y la tecnología Eye Care de LG (filtro de luz azul y funcionamiento flicker-safe). El diseño sin bordes en tres lados lo hace especialmente adecuado para montajes de doble monitor.",
    pros: ["Resolución 4K UHD en 27\": texto muy nítido", "Panel IPS con buenos ángulos de visión", "Conectividad USB-C", "Eye Care de LG: filtro de luz azul y flicker-safe", "Diseño sin bordes en tres lados"],
    cons: ["Sin altavoces integrados", "60 Hz: suficiente para trabajo, justo para juego", "Precio superior al de un equivalente Full HD"],
    specs: { "Tamaño": "27\"", "Resolución": "3840×2160 (4K UHD)", "Panel": "IPS", "Frecuencia": "60 Hz", "Conectividad": "USB-C", "Protección ocular": "LG Eye Care (flicker-safe + filtro luz azul)" },
    badge: "Mejor nitidez 4K",
    relatedPosts: ["mejor-monitor-home-office-2025", "monitor-4k-vs-full-hd-trabajo-remoto", "setup-trabajo-remoto-productividad-maxima"],
  },
  {
    slug: "dell-s2725qc-monitor-4k-usbc",
    name: "Dell S2725QC Monitor 4K 27\" Plus USB-C — 120Hz, altavoces",
    asin: "B0F29RSLHP",
    category: "Monitores",
    categorySlug: "monitores",
    categoryName: "Monitores para Home Office",
    price: "Consultar precio",
    priceMin: 0,
    rating: 4.5,
    reviewCount: 89,
    shortDescription: "Monitor 4K 27\" con USB-C, 120Hz, AMD FreeSync Premium, altavoces integrados y sRGB 99%. El mejor para home office.",
    fullDescription: "El Dell S2725QC es el monitor más completo del catálogo para trabajo remoto: reúne resolución 4K, 120 Hz de frecuencia de actualización, conectividad USB-C y altavoces integrados en un solo equipo. El USB-C transporta vídeo y carga del portátil por un único cable, lo que elimina el cargador del escritorio. La cobertura sRGB del 99% lo hace apto para trabajo con color, y la certificación Comfortview Plus (TÜV) reduce la emisión de luz azul sin alterar la fidelidad cromática. AMD FreeSync Premium completa un perfil que sirve igual para la jornada de trabajo que para el ocio.",
    pros: ["4K y 120 Hz en el mismo panel", "USB-C: vídeo y carga del portátil con un cable", "Altavoces integrados: no requiere audio externo", "sRGB 99% para trabajo con color", "Comfortview Plus con certificación TÜV"],
    cons: ["Los altavoces integrados no sustituyen a unos buenos auriculares", "Aprovechar los 120 Hz exige un equipo capaz de moverlos a 4K", "Precio superior al de un 4K a 60 Hz sin USB-C"],
    specs: { "Tamaño": "27\"", "Resolución": "3840×2160 (4K UHD)", "Panel": "IPS", "Frecuencia": "120 Hz", "Conectividad": "USB-C (vídeo + carga)", "Color": "sRGB 99%", "Audio": "Altavoces integrados", "Protección ocular": "Comfortview Plus (TÜV)", "Sincronización": "AMD FreeSync Premium" },
    badge: "Mejor overall",
    relatedPosts: ["mejor-monitor-home-office-2025", "monitor-4k-vs-full-hd-trabajo-remoto", "home-office-setup-productivo-guia"],
  },
  {
    slug: "benq-gw2790-monitor-eye-care",
    name: "BenQ GW2790 Monitor 27\" Eye-Care — FHD, Eyesafe, altavoces",
    asin: "B0CQ2YLVJR",
    category: "Monitores",
    categorySlug: "monitores",
    categoryName: "Monitores para Home Office",
    price: "Consultar precio",
    priceMin: 0,
    rating: 4.3,
    reviewCount: 210,
    shortDescription: "Monitor 27\" Full HD con certificación Eyesafe, filtro luz azul, altavoces integrados y panel IPS. Protección ocular certificada.",
    fullDescription: "El BenQ GW2790 es la opción del catálogo para quien prioriza el confort visual por encima de la resolución máxima. Su argumento principal es la certificación Eyesafe, un estándar independiente que verifica el espectro de luz emitido por el panel, más exigente que un simple modo de luz azul por software. Suma brillo automático adaptativo, que ajusta la pantalla a la luz ambiente de la habitación, panel IPS y altavoces integrados. Al ser Full HD en 27\", la densidad de píxeles es de unos 82 PPI: menor nitidez de texto que un 4K, a cambio de un precio más contenido y de no exigir nada al equipo.",
    pros: ["Certificación Eyesafe independiente", "Brillo automático adaptativo a la luz ambiente", "Panel IPS con altavoces integrados", "No exige un equipo potente para moverlo", "El más económico de la categoría"],
    cons: ["Full HD en 27\": unos 82 PPI, el texto se ve granulado frente a un 4K", "Sin USB-C con carga", "Menos espacio de trabajo útil que un 4K escalado"],
    specs: { "Tamaño": "27\"", "Resolución": "1920×1080 (Full HD)", "Panel": "IPS", "Frecuencia": "100 Hz", "Audio": "Altavoces integrados", "Protección ocular": "Eyesafe certificado + filtro de luz azul", "Brillo": "Automático adaptativo" },
    badge: "Mejor protección ocular",
    relatedPosts: ["mejor-monitor-home-office-2025", "monitor-4k-vs-full-hd-trabajo-remoto"],
  },
];

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(n: number): Product[] {
  return [...products].sort((a, b) => b.rating - a.rating).slice(0, n);
}
