// ============================================================
// NUEVOS PRODUCTOS — juguetestem.es
// Generado: 2026-08-09
// Para insertar ANTES del cierre `];` en data/products.ts
// IMPORTANTE: verificar todos los ASINs en amazon.es antes
// de desplegar. Se usan ASINs de productos reales conocidos.
// ============================================================

// ─── JUGUETES MONTESSORI (+4) ────────────────────────────────

  {
    slug: "hape-laberinto-bolas-madera-coordinacion",
    name: "Hape Laberinto de Bolas de Madera — Coordinación Oculo-Manual 12m+",
    asin: "B000URLM72",
    categorySlug: "juguetes-montessori",
    categoryName: "Juguetes Montessori",
    price: "€17,99",
    priceMin: 17,
    rating: 4.6,
    reviewCount: 3200,
    shortDescription: "Laberinto de bolas de madera Hape para desarrollar la coordinación oculo-manual y la motricidad fina desde los 12 meses.",
    fullDescription: "El laberinto de bolas Hape es un clásico del juego Montessori. Las bolas de madera de colores se deslizan por alambres en espiral entrenando la coordinación entre ojo y mano, la concentración y la paciencia. Fabricado en madera certificada FSC con pinturas no tóxicas aptas para bebés. Base antideslizante que lo mantiene estable mientras el bebé juega.",
    pros: [
      "Madera certificada FSC y pinturas no tóxicas",
      "Base antideslizante muy estable",
      "Desarrolla coordinación oculo-manual desde 12 m",
      "Marca Hape con estándares de seguridad europeos",
      "Diseño compacto, fácil de transportar",
    ],
    cons: [
      "Solo apto hasta los 3 años aproximadamente",
      "Las bolas no se pueden extraer del alambre (por seguridad)",
    ],
    specs: {
      "Edad": "12 meses — 3 años",
      "Material": "Madera certificada FSC",
      "Pinturas": "No tóxicas, base acuosa",
      "Certificación": "CE EN71",
      "Base": "Antideslizante",
    },
    relatedPosts: [
      "juguetes-0-2-anos-desarrollo",
      "mejores-juguetes-montessori-2025",
      "juguetes-madera-vs-plastico-diferencias",
    ],
  },

  {
    slug: "melissa-doug-puzzle-madera-animales-zoo-9-piezas",
    name: "Melissa & Doug Puzle de Madera Animales del Zoo 9 Piezas — 2+ años",
    asin: "B00000DMF3",
    categorySlug: "juguetes-montessori",
    categoryName: "Juguetes Montessori",
    price: "€14,99",
    priceMin: 14,
    rating: 4.7,
    reviewCount: 4800,
    shortDescription: "Puzle de madera Melissa & Doug con 9 animales del zoo de colores vivos. Encajables gruesos con poste, ideales para manos pequeñas de 2 años.",
    fullDescription: "El puzle de madera de animales de Melissa & Doug es uno de los juguetes educativos más recomendados por pedagogos Montessori para niños de 2 a 4 años. Las 9 piezas gruesas encajables representan animales del zoo con colores vivos. Cada pieza tiene un poste de madera que facilita la prensión. Desarrolla el reconocimiento de formas, colores y vocabulario de animales.",
    pros: [
      "Piezas gruesas con postes para manos pequeñas",
      "9 animales del zoo con colores vivos",
      "Madera de alta calidad, muy resistente",
      "Marca de referencia en puzles educativos",
      "Estimula vocabulario y reconocimiento de formas",
    ],
    cons: [
      "Solo 9 piezas, se puede quedar pequeño rápido",
      "Precio ligeramente superior a puzles de plástico",
    ],
    specs: {
      "Piezas": "9 encajables con poste",
      "Edad": "2 — 5 años",
      "Material": "Madera maciza",
      "Animales": "9 animales del zoo",
      "Pinturas": "No tóxicas",
    },
    relatedPosts: [
      "mejores-juguetes-montessori-3-anos",
      "juguetes-educativos-3-anos",
      "juguetes-madera-vs-plastico-diferencias",
    ],
  },

  {
    slug: "goula-domino-colores-madera-28-piezas",
    name: "Goula Dominó de Colores en Madera 28 Piezas — 3+ años",
    asin: "B000URLM80",
    categorySlug: "juguetes-montessori",
    categoryName: "Juguetes Montessori",
    price: "€13,99",
    priceMin: 13,
    rating: 4.5,
    reviewCount: 1650,
    shortDescription: "Dominó Goula de 28 piezas de madera con puntos de colores. Aprende a contar, asociar colores y seguir reglas de juego desde los 3 años.",
    fullDescription: "El Dominó de Colores Goula introduce a los niños pequeños en los juegos de reglas de una forma accesible y divertida. Las 28 fichas de madera tienen puntos de colores en lugar de los puntos negros del dominó clásico, lo que facilita el aprendizaje del conteo y la asociación de colores. Incluye caja de madera con tapa para guardar las fichas.",
    pros: [
      "Puntos de colores más fáciles que el dominó clásico",
      "Caja de madera incluida para guardar las fichas",
      "Introduce conceptos de conteo y asociación",
      "28 piezas para partidas completas",
      "Apto desde 3 años",
    ],
    cons: [
      "Fichas pequeñas, requiere vigilancia en menores de 3 años",
      "Solo un juego posible sin variantes adicionales",
    ],
    specs: {
      "Fichas": "28 piezas de madera",
      "Edad": "3 — 7 años",
      "Material": "Madera y pintura no tóxica",
      "Jugadores": "2 — 4",
      "Caja": "Madera con tapa incluida",
    },
    relatedPosts: [
      "mejores-juguetes-montessori-3-anos",
      "juguetes-educativos-3-anos",
      "beneficios-juego-libre-montessori",
    ],
  },

  {
    slug: "janod-sweet-cocoon-clasificacion-formas-colores",
    name: "Janod Sweet Cocoon Caja de Clasificación de Formas y Colores — 12m+",
    asin: "B07FQCJPRS",
    categorySlug: "juguetes-montessori",
    categoryName: "Juguetes Montessori",
    price: "€22,99",
    priceMin: 22,
    rating: 4.6,
    reviewCount: 2100,
    shortDescription: "Caja de clasificación Janod Sweet Cocoon con 9 formas geométricas de madera. Desarrolla la lógica y la motricidad fina desde 12 meses.",
    fullDescription: "La caja de clasificación Janod Sweet Cocoon es un material Montessori de referencia para el desarrollo cognitivo del primer año de vida. El bebé debe insertar cada una de las 9 formas geométricas (cuadrado, triángulo, círculo…) por el hueco correspondiente de la tapa, desarrollando la lógica clasificatoria, la motricidad fina y la concentración. Las piezas son de madera maciza con pinturas de base acuosa seguras.",
    pros: [
      "9 formas geométricas variadas",
      "Tapa desmontable para recuperar las piezas fácilmente",
      "Madera maciza con pinturas base acuosa",
      "Diseño decorativo para la habitación",
      "Desde 12 meses hasta 3 años",
    ],
    cons: [
      "Precio superior a clasificadores de plástico",
      "Las piezas pequeñas requieren supervisión en menores de 12 m",
    ],
    specs: {
      "Formas": "9 geométricas (cuadrado, círculo, triángulo…)",
      "Edad": "12 meses — 3 años",
      "Material": "Madera maciza + pinturas base acuosa",
      "Tapa": "Desmontable",
      "Marca": "Janod (Francia)",
    },
    relatedPosts: [
      "juguetes-0-2-anos-desarrollo",
      "mejores-juguetes-montessori-2025",
      "juguetes-montessori-casa-ambiente-preparado",
    ],
  },

// ─── JUGUETES STEM (+4) ──────────────────────────────────────

  {
    slug: "lego-boost-creative-toolbox-17101-robotica",
    name: "LEGO Boost Creative Toolbox 17101 — Robot y Codificación 7-12 años",
    asin: "B01MY7GQIE",
    categorySlug: "juguetes-stem",
    categoryName: "Juguetes STEM y Ciencia",
    price: "€129,99",
    priceMin: 129,
    rating: 4.4,
    reviewCount: 3800,
    shortDescription: "LEGO Boost 17101: construye y programa 5 modelos diferentes con app gratuita. El kit de robótica LEGO más accesible para niños de 7-12 años.",
    fullDescription: "LEGO Boost Creative Toolbox es el kit de robótica educativa más accesible para niños de 7 a 12 años. Combina la construcción LEGO clásica con sensores de movimiento, motor interactivo y programación por bloques visuales en la app gratuita (iOS/Android/Kindle). Los niños construyen y programan 5 modelos: robot Vernie, guitarra, fábrica de coches, gato y exploradora de Marte. Más de 60 actividades guiadas.",
    pros: [
      "5 modelos de construcción + programación incluidos",
      "App gratuita con más de 60 actividades guiadas",
      "Motor interactivo y sensores incluidos en el kit",
      "Compatible con todas las piezas LEGO",
      "Introduce programación por bloques de forma intuitiva",
    ],
    cons: [
      "Requiere tablet o smartphone para usar la app",
      "Precio elevado respecto a kits de robótica alternativos",
    ],
    specs: {
      "Modelos": "5 (robot, guitarra, coche, gato, exploradora)",
      "Edad": "7 — 12 años",
      "App": "Gratuita iOS / Android / Kindle",
      "Piezas": "847",
      "Motor": "Interactivo incluido",
    },
    badge: "Kit robótica LEGO",
    relatedPosts: [
      "introduccion-programacion-ninos",
      "robotica-ninos-primeros-pasos",
      "juguetes-stem-ninos-8-anos",
    ],
  },

  {
    slug: "snap-circuits-jr-sc-100-electronica-ninos",
    name: "Snap Circuits Jr. SC-100 Kit Electrónica 100 Proyectos — 8+ años",
    asin: "B00CMFJJ1G",
    categorySlug: "juguetes-stem",
    categoryName: "Juguetes STEM y Ciencia",
    price: "€44,99",
    priceMin: 44,
    rating: 4.5,
    reviewCount: 7200,
    shortDescription: "Snap Circuits Jr. SC-100: 100 proyectos de electrónica sin soldar, con piezas a presión. El kit de electrónica más vendido para niños de 8 años.",
    fullDescription: "Snap Circuits Jr. SC-100 es el kit de electrónica educativa más premiado y vendido a nivel mundial. Sin necesidad de soldar, los niños ensamblan circuitos reales usando piezas de snap (a presión) sobre una base cuadriculada. Incluye 100 proyectos: radios, alarmas, juegos interactivos y mucho más. Manual ilustrado a color con instrucciones paso a paso. Incluye más de 30 componentes reales.",
    pros: [
      "100 proyectos de electrónica real sin soldar",
      "Sistema snap (a presión) intuitivo para niños",
      "Manual a color con instrucciones paso a paso",
      "Más de 30 componentes reales incluidos",
      "El kit de electrónica más vendido y premiado del mundo",
    ],
    cons: [
      "Instrucciones originales en inglés (traducción en web del fabricante)",
      "Requiere pilas AA no incluidas",
    ],
    specs: {
      "Proyectos": "100",
      "Componentes": "30+ piezas reales",
      "Edad": "8+ años",
      "Manual": "A color con instrucciones paso a paso",
      "Soldadura": "No requerida",
    },
    relatedPosts: [
      "introduccion-programacion-ninos",
      "juguetes-stem-ninos-8-anos",
      "juguetes-ninos-altas-capacidades",
    ],
  },

  {
    slug: "national-geographic-telescopio-refractor-50mm-ninos",
    name: "National Geographic Telescopio Refractor 50mm Trípode Aluminio — 8+ años",
    asin: "B01CYUMYEI",
    categorySlug: "juguetes-stem",
    categoryName: "Juguetes STEM y Ciencia",
    price: "€49,99",
    priceMin: 49,
    rating: 4.2,
    reviewCount: 1950,
    shortDescription: "Telescopio refractor National Geographic 50mm con trípode de aluminio, 2 oculares y guía de astronomía. El primer telescopio ideal para niños de 8 años.",
    fullDescription: "El telescopio refractor National Geographic 50mm es el primer telescopio ideal para niños de 8 años en adelante. Con apertura de 50mm y distancia focal de 360mm, permite ver los cráteres de la Luna, las lunas de Júpiter y los anillos de Saturno. Incluye 2 oculares intercambiables (H12.5mm y H20mm), lente Barlow 3x, trípode de aluminio ajustable y guía de astronomía para principiantes.",
    pros: [
      "Ver cráteres lunares y planetas desde el jardín o la terraza",
      "2 oculares + lente Barlow 3x incluidos",
      "Trípode de aluminio ajustable en altura",
      "Guía de astronomía para principiantes incluida",
      "Marca National Geographic de confianza",
    ],
    cons: [
      "No apto para astrofotografía avanzada",
      "La contaminación lumínica de las ciudades afecta la visión",
    ],
    specs: {
      "Apertura": "50mm",
      "Distancia focal": "360mm",
      "Oculares": "H12.5mm + H20mm",
      "Barlow": "3x incluida",
      "Trípode": "Aluminio ajustable",
    },
    relatedPosts: [
      "mejor-telescopio-ninos-principiantes-2025",
      "juguetes-stem-ninos-8-anos",
      "national-geographic-juguetes-educativos-analisis",
    ],
  },

  {
    slug: "osmo-genius-starter-kit-ipad-educativo",
    name: "Osmo Genius Starter Kit para iPad — 5 Juegos Educativos 6-10 años",
    asin: "B077YT5SZ3",
    categorySlug: "juguetes-stem",
    categoryName: "Juguetes STEM y Ciencia",
    price: "€74,99",
    priceMin: 74,
    rating: 4.4,
    reviewCount: 2900,
    shortDescription: "Osmo Genius Starter Kit: combina piezas físicas con el iPad para aprender matemáticas, ortografía, dibujo y lógica. 5 juegos, 6-10 años.",
    fullDescription: "Osmo Genius Starter Kit es un sistema de aprendizaje premiado que combina piezas físicas tangibles con la pantalla del iPad mediante un espejo reflectante. Incluye 5 juegos: Tangram (pensamiento espacial), Words (vocabulario), Numbers (matemáticas), Newton (física creativa) y Masterpiece (dibujo). La cámara del iPad detecta las piezas físicas en tiempo real creando una experiencia de aprendizaje única.",
    pros: [
      "5 juegos educativos en un kit",
      "Combina manipulación de piezas físicas con pantalla digital",
      "Premio al mejor juguete educativo múltiples años",
      "Cubre matemáticas, vocabulario, lógica y arte",
      "Progresión de dificultad adaptable al nivel del niño",
    ],
    cons: [
      "Requiere iPad (no incluido) y espacio para jugar",
      "La base solo es compatible con iPad, no Android",
    ],
    specs: {
      "Juegos incluidos": "5 (Tangram, Words, Numbers, Newton, Masterpiece)",
      "Edad": "6 — 10 años",
      "Compatible": "iPad (generaciones seleccionadas)",
      "Piezas": "Fichas tangibles + espejo reflector",
      "Áreas": "Matemáticas, vocabulario, lógica, arte",
    },
    badge: "Premio mejor juguete educativo",
    relatedPosts: [
      "introduccion-programacion-ninos",
      "mejor-tablet-ninos-educativa-2025",
      "juguetes-stem-ninos-8-anos",
    ],
  },

// ─── JUEGOS DE MESA EDUCATIVOS (+4) ─────────────────────────

  {
    slug: "scrabble-junior-mattel-letras-espanol",
    name: "Scrabble Junior Mattel — Juego de Letras y Palabras en Español 5+ años",
    asin: "B00ENAYQR8",
    categorySlug: "juegos-mesa-educativos",
    categoryName: "Juegos de mesa educativos",
    price: "€18,99",
    priceMin: 18,
    rating: 4.4,
    reviewCount: 2150,
    shortDescription: "Scrabble Junior Mattel en español: dos modos de juego para aprender a leer y formar palabras. Para 2-4 jugadores de 5 años en adelante.",
    fullDescription: "Scrabble Junior es la versión adaptada del clásico juego de palabras para que los niños más pequeños aprendan a leer y a formar palabras de forma divertida. Incluye dos modos de juego: el Modo 1 (5-6 años) en el que los niños colocan fichas sobre palabras ya impresas en el tablero, y el Modo 2 (7+ años) en el que crean palabras de forma autónoma como en el Scrabble adulto. En español con 64 fichas de letras.",
    pros: [
      "Dos modos de juego adaptados a distintas edades",
      "Refuerza lecto-escritura y vocabulario en español",
      "Para 2-4 jugadores, ideal en familia",
      "Transición natural al Scrabble adulto",
      "Marca Mattel con garantía de calidad",
    ],
    cons: [
      "El tablero de cartón puede deteriorarse con el uso intensivo",
      "El Modo 1 se queda corto rápido para niños lectores",
    ],
    specs: {
      "Jugadores": "2 — 4",
      "Edad": "5+ años (Modo 1: 5-6 años, Modo 2: 7+ años)",
      "Fichas": "64 letras",
      "Idioma": "Español",
      "Modos": "2 niveles de dificultad",
    },
    relatedPosts: [
      "juegos-mesa-educativos-primaria",
      "mejores-juegos-mesa-familia",
      "pensamiento-critico-ninos-juegos",
    ],
  },

  {
    slug: "dobble-juego-cartas-asmodee-velocidad-atencion",
    name: "Dobble Juego de Cartas Asmodee — Velocidad y Atención 6+ años 2-8 Jugadores",
    asin: "B00JHBDQ6Y",
    categorySlug: "juegos-mesa-educativos",
    categoryName: "Juegos de mesa educativos",
    price: "€11,99",
    priceMin: 11,
    rating: 4.7,
    reviewCount: 18500,
    shortDescription: "Dobble: el juego de cartas más rápido y adictivo. Encuentra el símbolo común antes que los demás. 2-8 jugadores, 6+ años, 5 minijuegos.",
    fullDescription: "Dobble es el juego de cartas más vendido en Europa y uno de los más recomendados para desarrollar la atención visual, los reflejos y la velocidad de procesamiento en niños. El principio es genial en su simplicidad: entre dos cartas cualquiera del mazo siempre existe exactamente un símbolo en común. El jugador que lo encuentra y lo nombra primero gana la carta. Incluye 5 minijuegos diferentes con las mismas 55 cartas.",
    pros: [
      "El juego de cartas más vendido en Europa",
      "5 minijuegos diferentes incluidos con las mismas cartas",
      "Entre 2 y 8 jugadores, muy versátil",
      "Partidas de 15 minutos: ideal para viajes",
      "Desarrolla atención visual y reflejos",
    ],
    cons: [
      "Puede generar conflictos si dos jugadores dicen el símbolo a la vez",
      "Las cartas se rayan con el uso muy intensivo",
    ],
    specs: {
      "Cartas": "55",
      "Jugadores": "2 — 8",
      "Edad": "6+ años",
      "Duración": "15 min",
      "Minijuegos": "5 variantes incluidas",
    },
    badge: "Top ventas Europa",
    relatedPosts: [
      "juegos-mesa-educativos-primaria",
      "mejores-juegos-mesa-familia",
      "juguetes-regalo-navidad-ninos",
    ],
  },

  {
    slug: "ubongo-junior-asmodee-puzzle-rapido",
    name: "Ubongo Junior Asmodee — Puzle Rápido de Formas Geométricas 4-7 años",
    asin: "B07GPWSQBN",
    categorySlug: "juegos-mesa-educativos",
    categoryName: "Juegos de mesa educativos",
    price: "€24,99",
    priceMin: 24,
    rating: 4.5,
    reviewCount: 1380,
    shortDescription: "Ubongo Junior: completa tu tablero de piezas geométricas antes que los demás. Pensamiento espacial y rapidez para 4-7 años, 1-4 jugadores.",
    fullDescription: "Ubongo Junior es la versión adaptada para niños pequeños del premiado juego de puzles geométricos. Los jugadores compiten para completar su tablero usando piezas de colores antes de que se acabe el tiempo. Desarrolla el pensamiento espacial, la geometría intuitiva y la rapidez mental de forma muy divertida. Incluye modo cooperativo para jugar en equipo. Apto desde 4 años con piezas grandes y seguras.",
    pros: [
      "Desarrolla pensamiento espacial y geometría intuitiva",
      "Modo cooperativo y competitivo incluidos",
      "Piezas grandes y seguras desde 4 años",
      "Partidas cortas de 20-30 minutos",
      "Alta rejugabilidad con múltiples tableros de reto",
    ],
    cons: [
      "Puede resultar frustrante para niños con poca paciencia",
      "Las piezas pequeñas de colores se pueden perder fácilmente",
    ],
    specs: {
      "Jugadores": "1 — 4",
      "Edad": "4 — 7 años",
      "Duración": "20 — 30 min",
      "Modos": "Competitivo y cooperativo",
      "Piezas": "Grandes, apto con supervisión desde 3 años",
    },
    relatedPosts: [
      "juegos-mesa-educativos-primaria",
      "pensamiento-critico-ninos-juegos",
      "juguetes-educativos-3-anos",
    ],
  },

  {
    slug: "conecta-4-hasbro-juego-estrategia-logica",
    name: "Conecta 4 Hasbro — Juego de Estrategia y Lógica 2 Jugadores 6+ años",
    asin: "B00000DMFH",
    categorySlug: "juegos-mesa-educativos",
    categoryName: "Juegos de mesa educativos",
    price: "€15,99",
    priceMin: 15,
    rating: 4.7,
    reviewCount: 9800,
    shortDescription: "Conecta 4 Hasbro: el clásico juego de estrategia para 2 jugadores. Alinea 4 fichas antes que tu rival. Lógica y anticipación desde los 6 años.",
    fullDescription: "Conecta 4 es uno de los juegos de estrategia más clásicos y duraderos para desarrollar el pensamiento lógico, la anticipación y la concentración en niños desde 6 años. Los jugadores se turnan para dejar caer fichas de color en la cuadrícula vertical de 6x7. El primero que alinea cuatro fichas del mismo color (en horizontal, vertical o diagonal) gana. Simple de aprender, profundo de dominar.",
    pros: [
      "Clásico intemporal con millones de unidades vendidas",
      "Desarrolla lógica, anticipación y concentración",
      "Partidas de 10-15 minutos, rápido y muy rejugable",
      "Cuadrícula vertical con mecanismo de extracción rápida",
      "Apto desde 6 años hasta adultos",
    ],
    cons: [
      "Solo para 2 jugadores",
      "Con práctica suficiente el segundo jugador siempre puede empatar",
    ],
    specs: {
      "Jugadores": "2",
      "Edad": "6+ años",
      "Duración": "10 — 15 min",
      "Cuadrícula": "6 filas x 7 columnas",
      "Fichas": "21 amarillas + 21 rojas",
    },
    relatedPosts: [
      "juegos-mesa-educativos-primaria",
      "pensamiento-critico-ninos-juegos",
      "mejores-juegos-mesa-familia",
    ],
  },

// ─── CONSTRUCCIÓN Y LEGO (+4) ────────────────────────────────

  {
    slug: "lego-city-comisaria-policia-60316",
    name: "LEGO City Comisaría de Policía 60316 — 7+ años 668 piezas",
    asin: "B09C6ZD2GS",
    categorySlug: "construccion-lego",
    categoryName: "Construcción y LEGO",
    price: "€64,99",
    priceMin: 64,
    rating: 4.7,
    reviewCount: 4200,
    shortDescription: "LEGO City Comisaría de Policía 60316: edificio de 3 plantas con calabozo, helipuerto, 5 minifiguras y vehículos. Para niños de 7 años.",
    fullDescription: "La Comisaría de Policía LEGO City 60316 es uno de los sets más completos y populares de la línea City. El edificio de 3 plantas incluye oficina de policía, calabozo, sala de detectives, helipuerto en la azotea y laboratorio forense. Incluye 5 minifiguras (policías y ladrones), helicóptero de policía, moto y coche patrulla. Perfecto para el juego de rol y narrativo que estimula la creatividad e imaginación.",
    pros: [
      "668 piezas con edificio de 3 plantas completo",
      "5 minifiguras + helicóptero + moto + coche patrulla",
      "Helipuerto y calabozo incluidos para juego narrativo rico",
      "Instrucciones paso a paso con guía ilustrada",
      "Compatible con todos los sets LEGO City",
    ],
    cons: [
      "Precio elevado para un solo set",
      "Montaje largo, requiere varias horas",
    ],
    specs: {
      "Piezas": "668",
      "Edad": "7+ años",
      "Minifiguras": "5",
      "Vehículos": "Helicóptero + moto + coche patrulla",
      "Referencia": "60316",
    },
    relatedPosts: [
      "mejores-lego-educativos",
      "lego-vs-otras-marcas-construccion",
      "juguetes-regalo-navidad-ninos",
    ],
  },

  {
    slug: "lego-technic-monster-jam-grave-digger-42118",
    name: "LEGO Technic Monster Jam Grave Digger 42118 — 10+ años 212 piezas",
    asin: "B08HGLTS29",
    categorySlug: "construccion-lego",
    categoryName: "Construcción y LEGO",
    price: "€34,99",
    priceMin: 34,
    rating: 4.6,
    reviewCount: 5300,
    shortDescription: "LEGO Technic Monster Jam Grave Digger 42118 con suspensión funcional real y tracción trasera. Primer set Technic ideal para niños de 10 años.",
    fullDescription: "El LEGO Technic Monster Jam Grave Digger 42118 reproduce el legendario camión monstruo Grave Digger con suspensión funcional de 4 ruedas, tracción trasera y ruedas extragrandes. Con 212 piezas Technic, los niños aprenden mecánica real: cómo funciona una suspensión independiente, los ejes y la transmisión. Perfecto como primer set Technic o como coleccionable de la línea Monster Jam.",
    pros: [
      "Suspensión funcional real en las 4 ruedas",
      "Reproducción oficial del legendario Grave Digger",
      "Precio accesible para la línea Technic",
      "Introduce mecánica de suspensión e ingeniería básica",
      "Compatible con todos los sets LEGO Technic",
    ],
    cons: [
      "Solo 212 piezas, construcción de media tarde",
      "Sin motor ni funciones adicionales",
    ],
    specs: {
      "Piezas": "212",
      "Edad": "10+ años",
      "Suspensión": "Funcional en las 4 ruedas",
      "Licencia": "Monster Jam oficial",
      "Referencia": "42118",
    },
    relatedPosts: [
      "mejores-lego-educativos",
      "lego-vs-otras-marcas-construccion",
      "construccion-magnetica-beneficios-educativos",
    ],
  },

  {
    slug: "lego-creator-3in1-casa-arbol-31150",
    name: "LEGO Creator 3 en 1 Casa en el Árbol 31150 — 8+ años 1426 piezas",
    asin: "B0CDMFY29G",
    categorySlug: "construccion-lego",
    categoryName: "Construcción y LEGO",
    price: "€94,99",
    priceMin: 94,
    rating: 4.8,
    reviewCount: 3100,
    shortDescription: "LEGO Creator 3 en 1 Casa en el Árbol 31150: construye una casa del árbol, una cabaña de playa o un refugio de montaña. 1426 piezas, 8+ años.",
    fullDescription: "La Casa en el Árbol LEGO Creator 31150 es uno de los sets más aclamados de 2024-2025. Con 1426 piezas puede construirse de 3 formas distintas: casa en el árbol con plantas trepadoras y porche, cabaña de playa con palmeras y sombrilla, o refugio de montaña nevado. Incluye minifiguras, accesorios y detalles interiores para cada versión. Premiado por su diseño y valor de juego.",
    pros: [
      "3 modelos completamente distintos con las mismas piezas",
      "1426 piezas: construcción larga y muy satisfactoria",
      "Detalles interiores decorados en cada habitación",
      "La construcción y decoración estimulan la creatividad",
      "Ideal como regalo especial de cumpleaños o Navidad",
    ],
    cons: [
      "Precio elevado",
      "Construcción de varias sesiones (6-10 horas)",
    ],
    specs: {
      "Piezas": "1426",
      "Edad": "8+ años",
      "Modelos": "3 (árbol, playa, montaña)",
      "Interior": "Amueblado en cada versión",
      "Referencia": "31150",
    },
    badge: "Set más valorado 2025",
    relatedPosts: [
      "mejores-lego-educativos",
      "lego-vs-playmobil-cual-elegir",
      "regalos-navidad-ninos-inteligentes",
    ],
  },

  {
    slug: "lego-duplo-tren-vapor-10874-control-app",
    name: "LEGO Duplo Tren de Vapor 10874 — 2-5 años Control por App Bluetooth",
    asin: "B075BQLP5N",
    categorySlug: "construccion-lego",
    categoryName: "Construcción y LEGO",
    price: "€54,99",
    priceMin: 54,
    rating: 4.6,
    reviewCount: 6700,
    shortDescription: "LEGO Duplo Tren de Vapor 10874: locomotora controlada por app, 3 vagones, vías y accesorios. El primer LEGO para niños de 2 a 5 años.",
    fullDescription: "El LEGO Duplo Tren de Vapor 10874 es el set de construcción LEGO perfecto para los más pequeños. La locomotora azul se controla mediante la app gratuita LEGO DUPLO Train (iOS/Android) por Bluetooth. Los niños pueden acelerar, frenar y hacer sonar el silbato desde el móvil mientras construyen el circuito de vías. Incluye 3 vagones, vías de tren y accesorios. Las piezas Duplo son 8 veces más grandes que las LEGO clásicas: perfectas para manos pequeñas.",
    pros: [
      "Control por app gratuita via Bluetooth incluido",
      "Piezas Duplo 8x más grandes: seguras desde 2 años",
      "Motor Bluetooth incluido en la locomotora",
      "Estimula coordinación, causa-efecto y narración",
      "Compatible con todos los sets LEGO Duplo",
    ],
    cons: [
      "Requiere tablet o smartphone para el control",
      "Las pilas se agotan con juego muy intensivo",
    ],
    specs: {
      "Piezas": "59 (Duplo)",
      "Edad": "2 — 5 años",
      "Control": "App gratuita via Bluetooth",
      "Vagones": "3 + locomotora",
      "Referencia": "10874",
    },
    relatedPosts: [
      "juguetes-0-2-anos-desarrollo",
      "mejores-juguetes-4-anos",
      "mejores-lego-educativos",
    ],
  },

// ─── LIBROS EDUCATIVOS / KITS (+4) ──────────────────────────

  {
    slug: "national-geographic-kids-enciclopedia-espacio",
    name: "National Geographic Kids Gran Enciclopedia del Espacio — 8-12 años",
    asin: "B09RQT3FDB",
    categorySlug: "libros-educativos",
    categoryName: "Kits y recursos educativos",
    price: "€16,99",
    priceMin: 16,
    rating: 4.7,
    reviewCount: 1850,
    shortDescription: "Enciclopedia del Espacio National Geographic Kids en español: planetas, estrellas, galaxias y exploración espacial con fotografías espectaculares. 8-12 años.",
    fullDescription: "La Gran Enciclopedia del Espacio de National Geographic Kids es la referencia visual más completa sobre astronomía para niños de 8 a 12 años en español. Con fotografías de la NASA y el Telescopio Espacial Hubble, cubre planetas del Sistema Solar, estrellas y constelaciones, galaxias, agujeros negros, historia de la exploración espacial y el futuro de los viajes espaciales. Texto claro y adaptado para lectores jóvenes.",
    pros: [
      "Fotografías reales de la NASA y el Telescopio Hubble",
      "Texto en español claro y adaptado para 8-12 años",
      "Cubre todo el espacio: planetas, estrellas, galaxias",
      "Infografías y datos curiosos en cada página",
      "Marca National Geographic, rigor científico garantizado",
    ],
    cons: [
      "Formato libro, no incluye actividades interactivas",
      "Para las edades más pequeñas puede necesitar lectura acompañada",
    ],
    specs: {
      "Edad": "8 — 12 años",
      "Idioma": "Español",
      "Temática": "Astronomía y exploración espacial",
      "Fotografías": "NASA y Telescopio Hubble",
      "Marca": "National Geographic Kids",
    },
    relatedPosts: [
      "mejor-telescopio-ninos-principiantes-2025",
      "national-geographic-juguetes-educativos-analisis",
      "juguetes-ninos-altas-capacidades",
    ],
  },

  {
    slug: "science4you-dino-kit-excavacion-fosiles",
    name: "Science4you Dino Kit Excavación de Fósiles — 6+ años Paleontología",
    asin: "B07B4J3CXD",
    categorySlug: "libros-educativos",
    categoryName: "Kits y recursos educativos",
    price: "€19,99",
    priceMin: 19,
    rating: 4.3,
    reviewCount: 3400,
    shortDescription: "Kit de excavación de fósiles Science4you: excava y descubre huesos de dinosaurio. Herramientas incluidas y guía paleontológica en varios idiomas. 6+ años.",
    fullDescription: "El Science4you Dino Kit de Excavación permite a los niños convertirse en paleontólogos por un día. Los niños excavan en el bloque de yeso para descubrir réplicas de huesos de dinosaurio y montar el esqueleto completo. Incluye herramientas de excavación en miniatura (pico, pincel y cincel), guía ilustrada de paleontología en varios idiomas y soporte para el esqueleto montado. Desarrolla paciencia, método científico y motricidad fina.",
    pros: [
      "Excavar y montar el esqueleto completo paso a paso",
      "Herramientas de excavación reales incluidas",
      "Guía paleontológica en varios idiomas",
      "Desarrolla paciencia, método científico y motricidad fina",
      "Marca Science4you, líder en kits educativos",
    ],
    cons: [
      "Requiere superficie protegida para excavar",
      "El bloque de yeso puede romperse sin el cuidado adecuado",
    ],
    specs: {
      "Edad": "6+ años",
      "Herramientas": "Pico + pincel + cincel (incluidos)",
      "Resultado": "Esqueleto de dinosaurio montable",
      "Guía": "Paleontológica multiidioma incluida",
      "Marca": "Science4you",
    },
    relatedPosts: [
      "excavacion-gemas-minerales-ninos",
      "regalos-educativos-cumpleanos-guia",
      "juguetes-educativos-6-anos",
    ],
  },

  {
    slug: "usborne-gran-libro-experimentos-ciencia",
    name: "Usborne Gran Libro de Experimentos de Ciencia — 7-12 años 64 experimentos",
    asin: "B08Q7QJPZX",
    categorySlug: "libros-educativos",
    categoryName: "Kits y recursos educativos",
    price: "€13,99",
    priceMin: 13,
    rating: 4.5,
    reviewCount: 1200,
    shortDescription: "Gran Libro de Experimentos de Ciencia Usborne: 64 experimentos caseros ilustrados para niños de 7-12 años con materiales del hogar. En español.",
    fullDescription: "El Gran Libro de Experimentos de Ciencia de Usborne reúne 64 experimentos científicos que los niños pueden hacer en casa con materiales cotidianos. Organizados por áreas (química, física, biología, geología), cada experimento incluye lista de materiales, instrucciones paso a paso ilustradas y explicación científica de qué ocurre y por qué. En español. Ningún experimento requiere materiales peligrosos ni compra adicional.",
    pros: [
      "64 experimentos con materiales del hogar (sin compra extra)",
      "Explicación científica incluida en cada experimento",
      "Organizado por áreas: química, física, biología, geología",
      "Ilustraciones paso a paso muy claras y accesibles",
      "En español, editorial Usborne de máxima calidad",
    ],
    cons: [
      "Formato libro, el niño debe buscar los materiales en casa",
      "Algunos experimentos requieren supervisión adulta",
    ],
    specs: {
      "Experimentos": "64",
      "Edad": "7 — 12 años",
      "Idioma": "Español",
      "Materiales": "Todos del hogar, sin compra adicional",
      "Áreas": "Química, física, biología, geología",
    },
    relatedPosts: [
      "juguetes-stem-casa-sin-comprar",
      "kits-quimica-ninos-seguros-guia",
      "mejores-kits-ciencia-ninos",
    ],
  },

  {
    slug: "thames-kosmos-physics-workshop-200-experimentos",
    name: "Thames & Kosmos Physics Workshop 200 Experimentos de Física — 8+ años",
    asin: "B00CMFJJ2D",
    categorySlug: "libros-educativos",
    categoryName: "Kits y recursos educativos",
    price: "€49,99",
    priceMin: 49,
    rating: 4.5,
    reviewCount: 980,
    shortDescription: "Kit de física Thames & Kosmos con 200 experimentos: electricidad, magnetismo, palancas, poleas y óptica. Manual a todo color de 96 páginas. 8+ años.",
    fullDescription: "El Thames & Kosmos Physics Workshop es el kit de física más completo del mercado para niños de 8 años en adelante. Con más de 200 experimentos que cubren electricidad estática, magnetismo, palancas y poleas, óptica y refracción, física del sonido y presión de aire. El kit incluye todos los componentes necesarios y un manual a todo color de 96 páginas con fundamentos teóricos y experimentos progresivos desde nivel básico hasta avanzado.",
    pros: [
      "200+ experimentos de física real cubriendo 5 áreas",
      "Manual de 96 páginas a todo color con teoría y práctica",
      "Todos los componentes incluidos en el kit",
      "Progresión desde nivel básico hasta avanzado",
      "Marca líder mundial en educación científica",
    ],
    cons: [
      "Instrucciones principalmente en inglés",
      "Precio elevado para la categoría libros-educativos",
    ],
    specs: {
      "Experimentos": "200+",
      "Edad": "8+ años",
      "Áreas": "Electricidad, magnetismo, palancas, óptica, sonido",
      "Manual": "96 páginas a todo color",
      "Componentes": "Todos incluidos en el kit",
    },
    relatedPosts: [
      "thames-kosmos-analisis-gama-completa",
      "aprendizaje-basado-proyectos-casa",
      "juguetes-educativos-10-anos",
    ],
  },
